[package]
name = "fhe-eva-core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"] # Wichtig f체r WASM!

[dependencies]
wasm-bindgen = "0.2" # Wichtigste Abh채ngigkeit
# F체ge hier deine anderen Rust-Abh채ngigkeiten ein
